apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: heapster
    kubernetes.io/minikube-addons: heapster
    addonmanager.kubernetes.io/mode: Reconcile
  name: heapster
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8082
  selector:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: heapster
