apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/name: monitoring-influxdb
    kubernetes.io/minikube-addons: heapster
    addonmanager.kubernetes.io/mode: Reconcile
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    addonmanager.kubernetes.io/mode: Reconcile
    name: influxGrafana
